version: '3.3'
services:
  javadatabase3:
    image: mysql
    networks:
      - taskmanager-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD="admintest123"
      - MYSQL_DATABASE=javadatabase3
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

  frontend:
    image: ghcr.io/mitchell2001b/reactdemo3:master
    restart: always
    ports:
      - '8181:8181'

  backend:
    image: ghcr.io/mitchell2001b/semester3project:master
    ports:
      - '8080:8080'
    networks:
      - taskmanager-network
    depends_on:
      - javadatabase3
    restart: always
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://javadatabase3/javadatabase3",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "admintest123",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
# Names our volume
volumes:
  my-db:

networks:
  taskmanager-network:


