version: '3.3'
services:
  javadatabase3:
    image: mysql
    networks:
      - taskmanager-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=javadatabase3
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - my-db:/var/lib/mysql

  frontend:
    image: ghcr.io/mitchell2001b/reactdemo3:master
    restart: always
    build:
      context: ../../semester3react/reactdemo3
      dockerfile: ../../semester3react/reactdemo3/Dockerfile
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT

  backend:
    image: ghcr.io/mitchell2001b/semester3project:master
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    networks:
      - taskmanager-network
    depends_on:
      - javadatabase3
    restart: always
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://javadatabase3/javadatabase3",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
# Names our volume
volumes:
  my-db:

networks:
  taskmanager-network:


